### ISSUE TITLE
Repeated PayPal checkout option in cart payment section

### ISSUE THREAD

**Issue by ahsath** [snipcart/snipcart-v3-feedback#51]
**Integration URL**
If you can, provide an URL where we can see your Snipcart integration and reproduce the issue.
https://bariatricreloads.com/

**Describe the bug**
After filling shipping info in the payment section paypal appear twice

**To Reproduce**
1. Go to integration url
2. Add a product to the cart
3. Fill in the fields
3. Get to the payment section

**Expected behavior**
A single paypal checkout method

**Screenshots**
![image](https://user-images.githubusercontent.com/37009121/73127808-29f73d00-3f94-11ea-9564-832e2497c34a.png)

**Desktop (please complete the following information):**
 - OS: macOS X Catalina 10_15_0
 - Browser: Brave
 - Version: Chrome 79

**Additional context**
in 3.0.5 was working fine

**Comment by JeanSebTr** [comment]
Thanks for reporting this.

We released a fix directly in 3.0.6. No script update required.

**Comment by ahsath** [comment]
I'm using 3.0.6 and still having the same issue, you can check the integration url

**Comment by couellet** [comment]
Hey @ahsath I just purged our CDN cache for 3.0.6, tested it on your site and this is now fixed. Let me know if that's ok!
