### ISSUE TITLE
Unable to remove discount code in cart

### ISSUE THREAD

**Issue by sanketdjain** [snipcart/snipcart-v3-feedback#71]
**Integration URL**

**Describe the bug**
Unable to remove Promo discount code in cart.
 
**To Reproduce**
1. After adding a promo discount code in cart, there is no way to remove it and then add a different coupon code.
2. We could have multiple discount coupon codes and user may want to try a different discount promo code in the cart.

**Expected behavior**
User should be able to remove discount promo code from the cart.

**Screenshots**
![image](https://user-images.githubusercontent.com/1291796/86201524-a75f4480-bb14-11ea-90b5-78dbd08c3cae.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13
 - Browser: Firefox / Chrome
 - Version: latest

**Comment by thatfrankdev** [comment]
Thanks for submitting this @sanketdjain.

This is something we plan on bringing to v3 in a future release. Can't give an ETA for it at the moment though.

Cheers,

**Comment by sanketdjain** [comment]
@thatfrankdev 
On a desktop, after applying promo code, there is a Cancel button. When pressing cancel, the promo code is removed, but the discount stays on the cart. I would think this a bug. The user is shown the enter Promo code option , but the older discount on cart stays.

Do you think this behavior of Discount / Promo code should be prioritized as it is an inconsistent feature ?

Please let me know if you would like a separate issue for the Cancel Promo code.

**Comment by couellet** [comment]
Hey there,

We just released v3.0.20 yesterday that allows customers to replace mutually exclusive discounts. You can see more details in the release notes available here: https://docs.snipcart.com/v3/release-notes#v3020

**Comment by sanketdjain** [comment]
@couellet You have introduced a useful functionality to replace discounts. But you are still not allowing CANCEL option, in case customer does not want to apply any coupon.
